# Generated by Django 3.2.5 on 2021-08-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decided_shift',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('store_id', models.IntegerField()),
                ('year', models.DateField()),
                ('month', models.DateField()),
                ('day', models.DateField()),
                ('starting_time', models.DateTimeField()),
                ('closing_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hoped_shift',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('store_id', models.IntegerField()),
                ('cannot_work', models.CharField(max_length=50, verbose_name='出勤不可')),
                ('year', models.DateField()),
                ('month', models.DateField()),
                ('day', models.DateField()),
                ('starting_time', models.DateTimeField()),
                ('closing_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('business_stating_time', models.DateTimeField()),
                ('business_closing_time', models.DateTimeField()),
                ('closing_sunday', models.DateTimeField()),
                ('closing_monday', models.DateTimeField()),
                ('closing_tuesday', models.DateTimeField()),
                ('closing_wednesday', models.DateTimeField()),
                ('closing_thursday', models.DateTimeField()),
                ('closing_friday', models.DateTimeField()),
                ('closing_saturday', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=50, verbose_name='店舗')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('email', models.CharField(max_length=50, verbose_name='Eメール')),
                ('password', models.CharField(max_length=100, verbose_name='パスワード')),
                ('score', models.CharField(max_length=50, verbose_name='点数')),
                ('role', models.CharField(max_length=50, verbose_name='役割')),
                ('is_staff', models.CharField(max_length=50)),
                ('is_superuser', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.CharField(max_length=50)),
            ],
        ),
    ]
