# Generated by Django 2.1.7 on 2021-08-26 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shift_manager.models.user


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(default='name', max_length=50, verbose_name='名前')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Eメール')),
                ('password', models.CharField(max_length=100, verbose_name='パスワード')),
                ('score', models.CharField(blank=True, max_length=50, null=True, verbose_name='点数')),
                ('role', models.CharField(blank=True, max_length=50, null=True, verbose_name='役割')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', shift_manager.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DecidedShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('starting_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HopedShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.BooleanField(max_length=50, verbose_name='出勤可・不可')),
                ('date', models.DateField()),
                ('starting_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('business_stating_time', models.TimeField()),
                ('business_closing_time', models.TimeField()),
                ('closing_sunday', models.BooleanField(default=False)),
                ('closing_monday', models.BooleanField(default=False)),
                ('closing_tuesday', models.BooleanField(default=False)),
                ('closing_wednesday', models.BooleanField(default=False)),
                ('closing_thursday', models.BooleanField(default=False)),
                ('closing_friday', models.BooleanField(default=False)),
                ('closing_saturday', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='hopedshift',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shift_manager.Store'),
        ),
        migrations.AddField(
            model_name='hopedshift',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decidedshift',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shift_manager.Store'),
        ),
        migrations.AddField(
            model_name='decidedshift',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shift_manager.Store'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
